import { Person } from "./Person";

export const brusuloIhor: Person = {
  id: "14daf168-f902-4da6-9823-2670ccfee68b",
  firstName: "Ігор",
  lastName: "Брусило",
  birthDate: new Date(1980, 0, 1),
  photoUrl:
    "https://media.slovoidilo.ua/media/cache/person_thumb_exx/uploads/persons/origin/11/11717-brusilo-igor-mikolajovich_origin.png",
  education: [
    {
      start: null,
      end: null,
      degree: null,
      institutionId: "b2385521-63f6-4a16-a221-05dc3c9f9b7c",
      description: "Закінчив з відзнакою за спеціальнісю «Переклад»",
      actions: [],
    },
    {
      start: null,
      end: null,
      degree: null,
      institutionId: "f29cf37e-4ef0-4772-9ca4-80ef7e29336b",
      description: "Закінчив за спеціальнісю «Міжнародне право»",
      actions: [],
    },
  ],
  jobHistory: [
    {
      start: new Date(2002, 0, 1),
      end: new Date(2005, 0, 1),
      position: "Головний консультант Адміністрації Президента України",
      institutionId: "fe4654ce-6d30-4ab0-b23a-8909946caf0c",
      description: "",
      actions: [],
    },
    {
      start: new Date(2005, 0, 1),
      end: new Date(2007, 0, 1),
      position: "Головний консультант, заступника завідувача відділу",
      institutionId: "bd993b2d-0a84-4342-94a1-365f0b06dc04",
      description: "",
      actions: [],
    },
    {
      start: new Date(2007, 0, 1),
      end: new Date(2007, 0, 1),
      position: "Третій секретар, другий секретар",
      institutionId: "b651af32-8d69-433f-8695-fa7e7e0fafae",
      description: "",
      actions: [],
    },
    {
      start: new Date(2011, 0, 1),
      end: new Date(2011, 0, 1),
      position: "Заступник завідувача відділу",
      institutionId: "bd993b2d-0a84-4342-94a1-365f0b06dc04",
      description: "",
      actions: [],
    },
    {
      start: new Date(2012, 0, 1),
      end: new Date(2021, 0, 1),
      position: "Головний консультант",
      institutionId: "613b4738-1ac1-4ced-b745-229b6516f2fc",
      description: "Головний консультант, завідувач відділу, заступник Керівника Департаменту, перший заступник Керівника Служби, Керівник Служби Державного Протоколу та Церемоніалу Офісу Президента України",
      actions: [],
    },
    {
      start: new Date(2021, 2, 17),
      end: null,
      position: "Заступником Керівника",
      institutionId: "613b4738-1ac1-4ced-b745-229b6516f2fc",
      description: "Головний консультант, завідувач відділу, заступник Керівника Департаменту, перший заступник Керівника Служби, Керівник Служби Державного Протоколу та Церемоніалу Офісу Президента України",
      actions: [],
    },
  ],
  declarations: [],
  partyMembership: [],
  businesses: [],
  actions: [],
  investigations: [],
  family: [],
  criminalRecords: [],
  website: {
    url: "https://www.president.gov.ua/administration/office-management/zastupnik-kerivnika-ofisu-prezidenta-ukrayini-10",
    name: "Сайт президента України",
    icon: "website",
  },
  email: null,
};
