export default {
    CREATE_PERSON: 'ENTITIES/PERSONS/CREATE_PERSON',
    REQUEST_PERSON_DATA: 'ENTITIES/PERSONS/REQUEST_PERSON_DATA',
    UPDATE_PERSON_DATA: 'ENTITIES/PERSONS/UPDATE_PERSON_DATA',
    PERSON_DATA_RECEIVED: 'ENTITIES/PERSONS/PERSON_DATA_RECEIVED',
    CLEAR_PERSON_DATA: 'ENTITIES/PERSONS/CLEAR_PERSON_DATA',
    PERSONS_LIST_RECEIVED: 'ENTITIES/PERSONS/PERSONS_LIST_RECEIVED',
};
