export default {
  CREATE_INSTITUTION: "ENTITIES/INSTITUTIONS/CREATE_INSTITUTION",
  REQUEST_INSTITUTION_DATA: "ENTITIES/INSTITUTIONS/REQUEST_INSTITUTION_DATA",
  REQUEST_INSTITUTIONS_LIST: "ENTITIES/INSTITUTIONS/REQUEST_INSTITUTIONS_LIST",
  UPDATE_INSTITUTION_DATA: "ENTITIES/INSTITUTIONS/UPDATE_INSTITUTION_DATA",
  INSTITUTION_DATA_RECEIVED: "ENTITIES/INSTITUTIONS/INSTITUTION_DATA_RECEIVED",
  CLEAR_INSTITUTION_DATA: "ENTITIES/INSTITUTIONS/CLEAR_INSTITUTION_DATA",
  INSTITUTIONS_LIST_RECEIVED:
    "ENTITIES/INSTITUTIONS/INSTITUTIONS_LIST_RECEIVED",
};
