export default {
    CREATE_PARTY: 'ENTITIES/PARTIES/CREATE_PARTY',
    REQUEST_PARTY_DATA: 'ENTITIES/PARTIES/REQUEST_PARTY_DATA',
    UPDATE_PARTY_DATA: 'ENTITIES/PARTIES/UPDATE_PARTY_DATA',
    PARTY_DATA_RECEIVED: 'ENTITIES/PARTIES/PARTY_DATA_RECEIVED',
    CLEAR_PARTY_DATA: 'ENTITIES/PARTIES/CLEAR_PARTY_DATA',
    PARTIES_LIST_RECEIVED: 'ENTITIES/PARTIES/PARTIES_LIST_RECEIVED',
};
